import type { Metadata } from "next";
import { Playfair_Display, Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import GoogleAnalytics from "@/components/GoogleAnalytics";
import {
  META_DESCRIPTION,
  META_KEYWORDS,
  META_TITLE,
} from "@/lib/content";
import { SITE_NAME, SITE_URL } from "@/lib/site";

const display = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-display",
  display: "swap",
  weight: ["400", "700"],
});

const body = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-body",
  display: "swap",
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: META_TITLE,
    template: `%s — ${SITE_NAME}`,
  },
  description: META_DESCRIPTION,
  keywords: META_KEYWORDS,
  applicationName: SITE_NAME,
  authors: [{ name: SITE_NAME }],
  category: "Productivity",
  alternates: {
    canonical: "/",
    // hreflang is injected manually in <head> below — Next's metadata API
    // emits the camelCase attribute `hrefLang` which Google's parser does
    // not normalise, so the tags rendered but didn't count. Manual <link>
    // elements guarantee lowercase attribute names.
  },
  openGraph: {
    type: "website",
    locale: "en_IN",
    url: SITE_URL,
    siteName: SITE_NAME,
    title: META_TITLE,
    description: META_DESCRIPTION,
    // /opengraph-image is generated by app/opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title: META_TITLE,
    description: META_DESCRIPTION,
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-snippet": -1,
      "max-image-preview": "large",
      "max-video-preview": -1,
    },
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en-IN" className={`${display.variable} ${body.variable}`}>
      <head>
        {/* Manual hreflang — Next's metadata.alternates.languages emits
            camelCase `hrefLang` which Google's parser doesn't normalise.
            Writing the JSX prop as `hrefLang` ALSO emits camelCase in the
            rendered HTML (verified via curl after the first attempt at
            this fix). The spread-prop trick below bypasses React's
            known-attribute table and preserves the literal key, so the
            attribute renders as lowercase `hreflang` in the DOM. */}
        <link rel="alternate" {...{ hreflang: "en-IN" }} href={`${SITE_URL}/`} />
        <link rel="alternate" {...{ hreflang: "en" }} href={`${SITE_URL}/`} />
        <link rel="alternate" {...{ hreflang: "x-default" }} href={`${SITE_URL}/`} />
      </head>
      <body className="min-h-screen bg-cream font-sans text-navy antialiased">
        {children}
        <GoogleAnalytics />
      </body>
    </html>
  );
}
