/**
 * Curated list of well-known disposable / throwaway email providers.
 *
 * Goal: defeat the most casual abuse of the freemium gate ("one analysis per
 * email" becomes "infinite analyses if you can spin up mailinator addresses").
 * The full upstream list is ~3000 domains; this is the long-tail-pruned
 * version covering the ~50 providers that produce ~95% of disposable
 * addresses in the wild as of 2026.
 *
 * Add domains to this set when abuse logs (Vercel `[analyze] gate failed: …`
 * lines) show a new pattern. Do NOT add legitimate forwarding services
 * (e.g. SimpleLogin, AnonAddy / Addy.io, Apple Hide My Email) — those are
 * privacy-preserving aliases for real inboxes, not throwaways.
 */
export const DISPOSABLE_EMAIL_DOMAINS = new Set<string>([
  // Top global throwaway providers
  "mailinator.com",
  "mailinator.net",
  "mailnator.com",
  "10minutemail.com",
  "10minutemail.net",
  "10minutemail.co",
  "10minutesemail.com",
  "guerrillamail.com",
  "guerrillamail.info",
  "guerrillamail.biz",
  "guerrillamail.de",
  "guerrillamail.org",
  "guerrillamail.net",
  "sharklasers.com",
  "grr.la",
  "tempmail.com",
  "tempmailaddress.com",
  "tempmail.de",
  "tempmail.us.com",
  "tempemail.com",
  "tempinbox.com",
  "tempinboxes.com",
  "throwawaymail.com",
  "throwam.com",
  "throw-away.email",
  "trashmail.com",
  "trashmail.net",
  "trashmail.io",
  "trbvm.com",
  "trash-mail.com",
  "yopmail.com",
  "yopmail.fr",
  "yopmail.net",
  "fakeinbox.com",
  "fakemail.fr",
  "fakemailgenerator.com",
  "spambox.us",
  "spam4.me",
  "spam.la",
  "spamgourmet.com",
  "spambog.com",
  "spamfree24.com",
  "deadaddress.com",
  "dispostable.com",
  "discardmail.com",
  "discardmail.de",
  "maildrop.cc",
  "mail.tm",
  "mailtm.com",
  "mailpoof.com",
  "mintemail.com",
  "moakt.com",
  "mohmal.com",
  "emailondeck.com",
  "emailfake.com",
  "getnada.com",
  "getairmail.com",
  "burnermail.io",
  "tempr.email",
  "1secmail.com",
  "1secmail.org",
  "1secmail.net",
  "esiix.com",
  "wwjmp.com",
  "soodonims.com",
  "anonbox.net",
  "anonymbox.com",
  "tafmail.com",
  "tmpmail.org",
  "tmpmail.net",
  "tmpeml.com",
  "vomoto.com",
  "wegwerfmail.de",
  "wegwerfmail.net",
  "wegwerfmail.org",
  "linshiyou.com",
  "linshiyouxiang.net",
  "mailcatch.com",
  "mailnesia.com",
  "mailmoat.com",
  "minutemail.com",
  "mvrht.com",
  "nwldx.com",
  "objectmail.com",
  "opayq.com",
  "owlpic.com",
  "spamex.com",
  "rcpt.at",
  "snapwet.com",
  "supermailer.jp",
  "tafoi.gr",
  "temp-mail.org",
  "temp-mail.io",
  "tempmailo.com",
  "tempinbox.xyz",
  "tempmailbox.net",
  "trillianpro.com",
  "tyldd.com",
  "uggsrock.com",
  "veryrealemail.com",
  "yopmail.gq",
  "armyspy.com",
  "cuvox.de",
  "dayrep.com",
  "einrot.com",
  "fleckens.hu",
  "gustr.com",
  "jourrapide.com",
  "rhyta.com",
  "superrito.com",
  "teleworm.us",
]);
